// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCrPJTKSbOu1xyJEpiCSwmlLBJRnPu0fMM',
    appId: '1:37203192483:web:fea3e92b7492c33892ad16',
    messagingSenderId: '37203192483',
    projectId: 'billbro-8b689',
    authDomain: 'billbro-8b689.firebaseapp.com',
    storageBucket: 'billbro-8b689.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCJz7NzGrwxmbyOR9ndpGpzWKnIY-0Uc-g',
    appId: '1:37203192483:android:b79446c916ef940f92ad16',
    messagingSenderId: '37203192483',
    projectId: 'billbro-8b689',
    storageBucket: 'billbro-8b689.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAGV3IcZdlVTzLb3TBsiNaISIYiYlWiiVU',
    appId: '1:37203192483:ios:a53306c39f82fa0392ad16',
    messagingSenderId: '37203192483',
    projectId: 'billbro-8b689',
    storageBucket: 'billbro-8b689.firebasestorage.app',
    iosBundleId: 'com.example.billbro',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAGV3IcZdlVTzLb3TBsiNaISIYiYlWiiVU',
    appId: '1:37203192483:ios:a53306c39f82fa0392ad16',
    messagingSenderId: '37203192483',
    projectId: 'billbro-8b689',
    storageBucket: 'billbro-8b689.firebasestorage.app',
    iosBundleId: 'com.example.billbro',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCrPJTKSbOu1xyJEpiCSwmlLBJRnPu0fMM',
    appId: '1:37203192483:web:b95929619213352292ad16',
    messagingSenderId: '37203192483',
    projectId: 'billbro-8b689',
    authDomain: 'billbro-8b689.firebaseapp.com',
    storageBucket: 'billbro-8b689.firebasestorage.app',
  );
}
